import torch

LEARNING_RATE = 1e-5
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
BATCH_SIZE = 4
NUM_EPOCHS = 20
NUM_WORKERS = 2

ROOT_FOLDER = r"E:/DATN_local"

IS_COLAB = True
if IS_COLAB:
    ROOT_FOLDER = "/content"
    BATCH_SIZE = 16

DATASET = ROOT_FOLDER + r"/1_IN_USED_DATASET"


EXPERIMENT_NAME = "UNET_WITH_RESIDUAL_CLASSIFICATION"

CHECK_POINT_MASK_NAME = "UNET_WITH_RESIDUAL_DICE_LOSS.pth.tar"

# image size must be divisible by 32, because U-Net structure has 5 bi-down_sample
IMAGE_HEIGHT = 512
IMAGE_WIDTH = 512

PIN_MEMORY = True
LOAD_MODEL = True

TRAIN_IMG_DIR = DATASET + r"/TRAIN_DEV"
TRAIN_MASK_DIR = DATASET + r"/TRAIN_DEV_MASK"

# USE random split so dont need to input this
VAL_IMG_DIR = ""
VAL_MASK_DIR = ""

TEST_IMAGE_DIR = DATASET + r"/TEST"
TEST_MASK_DIR = DATASET + r"/TEST_MASK"

OUTPUT_FOLDER = ROOT_FOLDER + "/1_EXPERIMENT_OUTPUT/" + EXPERIMENT_NAME

import os
if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)


CLASSIFICATION_LABEL = DATASET + r"/level_label.json"

CHECKPOINT_PATH =  ROOT_FOLDER + r"/MODEL_CHECKPOINTS/" + CHECK_POINT_MASK_NAME
CHECKPOINT_FULL_PATH = ROOT_FOLDER + r"/MODEL_CHECKPOINTS/" + "FOR_FUTURE_USE"

IS_TRAINING_CLASSIFIER = True


